### ISSUE TITLE
After latest melpa update: command-line: Symbol’s value as variable is void: < 

### ISSUE THREAD

**Issue by pbgc** [nex3/perspective-el#93] opened 2019-09-16 13:51 UTC
Hi,

After last update from melpa I got this error:

command-line: Symbol’s value as variable is void: <

The strange thing is that if I clone  this rep and use HEAD I don't get the error and everything works.

Thanks in advance

**Comment by pbgc** [comment] 2019-09-16 14:08
Just removed perspective and pers-projectile and installed again and it now works ...
I really can't understand what happened ... I didn't touch anything.
Sorry!

**Comment by jkdufair** [comment] 2020-02-28 23:08
I just ran into this issue updating from Melpa. Glad to help troubleshoot.

**Comment by gcv** [comment] 2020-02-28 23:49
Let's try to get to the bottom of this. A few things to look at.

1. Did you restart Emacs after updating your packages? Try that first.
2. Look in the perspective installation directory. Is the perspective.elc file stale by any chance (older than perspective.el)?

**Comment by pbgc** [comment] 2020-03-02 11:39
@pbgc I closed the issue before ... but I get this every time I update from melpa ....

It happened again today! 
1 - I restarted Emacs after updating (and I get the error)
2 - perspective.elc has the exact timestamp of perspective.el

The way I solve this every time is to remove: projectile, perspective and persp-projectile and reinstall them again ..

**Comment by jkdufair** [comment] 2020-03-02 14:26
And, to add a data point, the error does not occur until after one restarts Emacs (which I suppose isn't entirely necessary, but I do it once a week when I update packages)

**Comment by gcv** [comment] 2020-03-02 18:32
I reproduced something similar to this problem, but it took some head-scratching and I am _not_ certain I hit the bug exactly the same way as @jkdufair or @pbgc, so we have more work to do.

This seems to happen when an elc file loads and hits undefined references. In my case, the `<` is a red herring, and the missing reference is most likely something else. I reproduced the problem by byte-compiling an old version of Perspective which does not have `persp-ivy-switch-buffer` and using the following use-package form:

```
(use-package perspective
  :defer nil
  :bind (("C-x C-M-b" . persp-ivy-switch-buffer))
)
```

This causes a failure on startup: `Error (use-package): perspective/:catch: Symbol’s value as variable is void: <`. This gave me a clue about where to dig. I put `(setq use-package-verbose 'debug)` right after the use-package, and restarted Emacs. That created a `*use-package*` buffer which gave somewhat more useful error information, and I tracked down the reference to a missing function.

Note that deleting `perspective.elc` moves the error from load-time to run-time, i.e., it does not occur unless I invoke the key binding.

However, it looks like you guys are hitting the problem with the prefix `command-line`. I'm not sure what that is. Are you aware of any package or command called that which might invoke `persp-*` functions? Do you have any custom macros or keybindings which refer to `persp-*` functionality?

Could you please post your `use-package` forms if you have them, or any code you use to bootstrap Perspective manually?

**Comment by pbgc** [comment] 2020-03-02 18:37
@gcv 

I'm not using use-package ... yes I know I should :) but have a very big setup and never bothered to change.
The lines I have for perspective are:
`(require 'perspective)
(persp-mode)

(defun my/persp-neo ()
       "Make NeoTree follow the perspective"
       (interactive)
       (let ((cw (selected-window))
             (path (buffer-file-name))) ;;save current window/buffer
             (progn
               (when (and (fboundp 'projectile-project-p)
                          (projectile-project-p)
                          (fboundp 'projectile-project-root))
                 (neotree-dir (projectile-project-root)))
               (neotree-find path))
             (select-window cw)))


(add-hook 'persp-switch-hook  'my/persp-neo)

(require 'persp-projectile)
(define-key projectile-mode-map (kbd "H-s") 'projectile-persp-switch-project)`

**Comment by gcv** [comment] 2020-03-02 18:42
Can you reproduce the error if you comment out everything except the first two lines (the ones loading perspective)?

**Comment by pbgc** [comment] 2020-03-02 18:45
@gcv How can I try to do that ? Because the error only happens to me after upgrading the package ... (just did it today). After removing it and reinstalling again (already did it unfortunately) it does not happen anymore until next update.

**Comment by gcv** [comment] 2020-03-02 19:03
This is one of many reasons why I keep my ELPA packages under my own source control. :)

Anyway: I just pushed a small README update I've been meaning to make anyway. Not sure how long MELPA takes to run a build, but you'll be able to upgrade again soon. Before you do this, though, make a copy of the current perspective-* directory in your elpa installation directory and put that copy somewhere outside the Emacs tree. That way you'll be able to rerun the update repeatedly while we figure out what is going on in your setup.

**Comment by gcv** [comment] 2020-03-02 19:13
One more thing: do you byte-compile your init file?

**Comment by jkdufair** [comment] 2020-03-02 20:01
```
  (use-package persp-projectile)

  (use-package perspective
	  :config
	  (require 'persp-projectile)
	  (setq persp-show-modestring 'header)
	  (persp-mode-set-prefix-key (kbd "C-c r"))
	  (persp-mode)
	  (persp-switch "main"))
```

Looks like mine might be related to using `persp-projectile`

Perhaps I'm not configuring the use of the two correctly?

**Comment by jkdufair** [comment] 2020-03-02 20:02
Also, my init file is an org file and it get's org-tangled on startup. Not sure if that results in byte compilation or not.

**Comment by gcv** [comment] 2020-03-02 21:32
@jkdufair: Your configuration looks fine, but I've learned to ignore my instincts on this when the Emacs byte-compiler gets involved. :'(

Let's start with something simple. Does the error occur on Emacs startup, or only after you invoke a persp-mode command? If it's on startup, put `(setq use-package-verbose 'debug)` immediately after your use-package bootstrapping code. That should give you a `*use-package*` buffer with detailed errors. Please post that.

Another thing to try: comment out everything to do with persp-projectile (the use-package form  and the require). Does that make the error go away?

**Comment by pbgc** [comment] 2020-03-03 09:59
@gcv still waiting for elpa. I have currently perspective-20200301.1858 that I updated yesterday.

I don't byte compile my init file ... I don't restart emacs often and I don't bother.

**Comment by gcv** [comment] 2020-03-03 18:24
Looks like MELPA didn't pick up the change I made since it was just to the README, which is not included in the build recipe. I just made a small change to the main source file, so that should get picked up. Try again soon.

**Comment by pbgc** [comment] 2020-03-03 22:47
@gcv finally could update.
I repeated the process without and with the extra lines on init.el (copying into .emacs/elpa the folder previously copy to another place out of .emacs) ... and the update was done without the error :(

**Comment by gcv** [comment] 2020-03-04 01:32
Oh boy.

A few weeks ago, I made some changes in how Perspective handles references to external packages, so that may have made the problem go away..?

Definitely waiting to hear more reports.

**Comment by pbgc** [comment] 2020-03-09 10:34
@gcv updated today from melpa and got the error after restarting emacs.
I made a copy of the previous version.

**Comment by gcv** [comment] 2020-03-09 20:08
I think I found the problem, and yeah, it's related to the huge footgun that is Emacs eager macroexpansion. The cleanest fix is to disable byte-compiling perspective.el. I really don't want to do this, and need to think if I can work around it.

**Comment by gcv** [comment] 2020-03-10 05:57
All right, I committed a workaround: https://github.com/nex3/perspective-el/commit/920d15ef85cd17fb3ab18afc5b0dd5d47dba8852

Give this a try when it hits MELPA and let me know if it made the problem go away.

**Comment by pbgc** [comment] 2020-03-10 11:12
@gcv  I just updated to 20200310.552 without error !

**Comment by jkdufair** [comment] 2020-03-10 13:08
I was also successful upgrading. Thanks so much @pbgc for this glorious ugly hack.

**Comment by gcv** [comment] 2020-03-10 17:38
Great news! This is important enough that I tagged a new version for the long-suffering MELPA Stable users.

**Closed by gcv** 2020-03-10 17:38 UTC
