### ISSUE TITLE
does not work with emacs 26.1

### ISSUE THREAD

**Issue by phenix3443** [nex3/perspective-el#78] opened 2019-01-16 07:00 UTC
(use-package perspective
  :ensure t
  :disabled
  :config
  (persp-mode)
  )

(use-package persp-projectile
  :after (projectile perspective)
  :disabled
  :ensure t
  :config
  ;; (define-key projectile-mode-map (kbd "s-s") 'projectile-persp-switch-project)
  )

when start emacs, show error:
Error (frameset): Wrong type argument: perspective, "Unprintable entity"

**Comment by dzop** [comment] 2019-05-23 16:20
I'm on

```
GNU Emacs 26.1.92 (build 2, x86_64-apple-darwin18.2.0, Carbon Version 158 AppKit 1671.2) of 2019-04-13
```

and I don't experience such an error. Also `frameset` functions are never called by perspective which makes me suspect that the error your are getting has to do with some other package interacting badly with perspective.

**Comment by gcv** [comment] 2019-09-27 19:21
@phenix3443: Any idea what other package might be causing perspective incompatibility? As things stand, packages which create frames with `after-make-frame-functions` bound to `nil` will cause all kinds of interesting perspective bugs. We'll try to resolve that soon.

**Comment by gcv** [comment] 2019-11-26 03:49
Closing this ticket, since we now have a test suite and cannot reproduce it. Please reopen if you still have problems.

**Closed by gcv** 2019-11-26 03:49 UTC
