### ISSUE TITLE
emacsclient crashes with error *ERROR*: Perspective `main` already exists

### ISSUE THREAD

**Issue by tmccombs** [nex3/perspective-el#51] opened 2015-09-22 23:18 UTC
Sometimes, if I already have an emacsclient open (typically a gui window) and try to start another one (typically a terminal client), emacsclient will die  immediately

If I start it with emacsclient -c it give me this:
 `*ERROR*: Perspective`main`already exists`.

If I start with emacsclient -t it just really messes up my terminal because it starts to layout the emacs screen but then crashes in a bad state.

It looks like this error message comes from persp-rename. I'm not sure why persp-rename is called when emacsclient starts. But even if it causes a problem I don't think it should crash the client.

**Comment by tmccombs** [comment] 2015-09-24 21:50
I have emacsclient -t setup as my editor for git, and use magit. It looks like this happens when there is an auto-merge when I do a merge.

**Comment by zenspider** [comment] 2019-11-27 05:39
Cannot reproduce. This is 5 years old... I suspect it isn't valid anymore. Closing.

**Closed by zenspider** 2019-11-27 05:39 UTC
